tailscale: ENC[AES256_GCM,data:1z19ZbqOqLylIFwZNPts/O9GsySKP7tpR5Yhn8qyUZikqsaNoc/i6+eB8KB7GS+SblGXJKDHY9lokdSq3w==,iv:x3Q/Zx5z4odEWvZ4QS0/SM6n1MhxQm7PXs/7wpkz+IQ=,tag:aUDfr6s1pPvFN2aNs56/mw==,type:str]
hashed_password: ENC[AES256_GCM,data:R7RdPsOoY+pBWieZ5e5BGWvIfex9ymKKLAtwwc6BN1ltxZdmkEy042XmZExR2Mimvc+EYN0dlo/+eY0XPaO5GuwJ36f9Fw80bWxSc40IcyqGkFYIdMvcKN0y6RE6TfMDsYn0TBd7TZzoDg==,iv:mfBUcyqTXyJEVJgxmxQjbtMKQECNCTXzl1nfFwDsyck=,tag:2zkcy69sNg1LX0v117mf6g==,type:str]
copilot_api_key: ENC[AES256_GCM,data:hrLRUgHq1bTX9NpT1Mqo62zNx4Qpjt286JzPK0WeCTVyLdupWVWBqgMuLe/cH15keOORfS7IVTQtpHuj59L0YLFOicBNM0KJ,iv:gRAxZ9exJipBY3ZzpWV9W72lUCOjjWK5qND0a2CBtWo=,tag:Bfjkferhlxyj0bY7NAN2tw==,type:str]
spotify_user: ENC[AES256_GCM,data:94nhjnkpWG0D5RdDpjrESDF/xN+79M+0WA==,iv:0ZiKx1PhykOKFCpzL8bKiVbPL53RGcsh1X6w0D1fwB8=,tag:7OJSN8VxLtoL+oAys7Mt9Q==,type:str]
spotify_pass: ENC[AES256_GCM,data:73XteOQPdxz6QLTm4dYkJPUFwighNe5XOg==,iv:+k2kSKwuEFK7r49krDPp1nc5z9Gp3/qHVJet51aODY0=,tag:0Ib1qIcoyHVWUdKDCOhYGg==,type:str]
cachix-agent: ENC[AES256_GCM,data:qdlwzooqpMOYKqy+8fMWarHq19t+AsEYc0ZIOiChtW9qVsJG3Dl30kBOQpt0Gi8zN8v7lT6NGpAY3z0Va4oDYcH6JwgKXbnVJ+AGlrHAekkU2TR9/CXbJ3KNqKzPfqn7yMMbpNo40DOAI7jj9qZvUVZgthONwc6B/PqB+hdDpINtB7Hqc2R8E/MQj4AwGQVPaKdQXxl4x/KUSGMQ0Jharq0xeIaGe0ox,iv:B9cNVF3Win7q3X7bJkAvsMdkt87hYGeDy6T+GxFKz/E=,tag:kqBIwu2ml30JIUxmagi+Zw==,type:str]
cachix: ENC[AES256_GCM,data:c+VVgRPQYyWjEQTDZjjJ33e/2lFHGkOX0PbXUanu8ltZqSQFtDq+cZUgHIvu/8AHXOR/TC9IhzvPgUN9O4yOk9Wz04dLEKxhIalvu/vK06exp1TXS1gZGeOSBCxz4y/UCz2inlik071Q8Ss4XqAdOiq/AeVI5ISHvwRFECaFqB6pr14+c0+y+2TxVn4P01VAiLqrzPVi7abs0b+n9o0YnIjqlm+OUEMOMpHcxIlAUp/7PE3Up66yIMnnFKAMtfxbk1vAT1Vlp/5PyOUKRHQ8sXjFH6jqbQId2950LxfKuZOL84yiyUhu9VEgwJXKMsjS+dlPL0o9OgHCv73ZkIG6jE1k7/o8fef7OSPxUhXzQKTwIs6aG1FmAkROtnWjStXfUqahd5PvzyfV6bnhW7YWn6L5yW/RodWa5ytFkPXXoY70YQOGMOkwK8gjOjnfYrinhoeatIbAt+M=,iv:JapqETrRX2fqX2+MEibIrz07FbT7D8/gqE4Zn6SaT/w=,tag:qewxNtReXtzVTCNC5tQYzg==,type:str]
cameron_ssh_key: ENC[AES256_GCM,data:3+ueaPlbS/zNRPEEsLS+txuMN1GCOpzsnZ36dhomlh/emwKAnrN6BZyilpGDWqCYn7Wy5AOHKx9rtBwtL/vaC1X6d/kbwJErLZIEvPY4ElbwMRyPrbKCWCvMviBjRWE79t+hXhbsw8US6YDlqspvrL4x/BvHJg5CHbbYkkjrQxLFUWFzuZeR99Qyo/OP9avGHP3ZO+dONGQuR1TGRG3rSTWboXrNGxehIgHpEZ1UiBjT/CQMH5ycGfxzzVNDRko5++b8o+sqf71ExBNU8lVH8t8LjFklY/zxBPYp3xdWbFMwws8NJT27um6vjRHGE5OG1cy+x4mXLMAWOtSMSSE4ncetB8/uCZEUCaS4JKkXtWf0lb7sMAIIikbtVRf6UBH6G/TLvL4KjvU6dUg3ElXyWKvwRzoFNnCCFrjepdSIe609jjWqu13I6PTYrevmcEyoroMl6D/PMLl7DrnhKC/IXPPn87WUC6neUu4D17bIr7r7yKWQ+7h3MHmC8HJ8yS4UQcRRmxkrRP0tKcq2A/0lckoKoHRdY9FrJzIY,iv:gI1ML9IEbGYaMkbMXvXTANPhu5LfMjRRFSDfGtWPYa8=,tag:4p9oeKMbrExJ+mmLShV/cQ==,type:str]
immich: ENC[AES256_GCM,data:nCXLZDeYjEK4dNs8sqRhdx68Pto/W/khhD7GHTWIOhmRJu+DGQ==,iv:o97a/XaqHnvy5gSYJvNL68EazargqJdtvKgcECGXnqk=,tag:sQRliktbmhdilhYrsXCQ+Q==,type:str]
sops:
    age:
        - recipient: age1a35mrj6kgp9uvchw8r59q8ma6wdyllmzfyn0ek56ez8jag4gfu4q6rkuuq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZU1oUmRBVW9RVnhuZ01x
            MXM1SVpZQkgxbmhwRXVrNGR5dTYzKy9oaUVvCjg1NXVlMkM0dFF5QlI3SEVrcUlE
            UGpNSWxkVnFpMmx2T0hmSTM0OVlPS0UKLS0tIFZlQ2w1bU84S3hueFJlYXBnUzZo
            b0ZvOSs1R09wTzZ3SHQ2YkZWQmQ0RE0KeSDwQxOuOEzn3WWcB2Nyf3Kze/Py3Suw
            hCt+yLUVknL+6C2LYlwlsnvFQnZc/CUfXQpnfiP3lkibO1t3g9BL+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vfq6fselrwr9cl3udvx96ldpakzfdhaf8rl5sl9ztg5heq8pjswserwwhe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZGgycFFrQkN1TXNxUlJW
            ZjJCb0NtVUlwcDRvOUQ2NWRHMkhYQWF3dWhRCjVLQmhOL2Q1TjFJV2xlR3FteWVC
            VTRNeHpZM2lpM1FpcTVETGhwVkJFUDgKLS0tIDE3OGxmbFcrMHZsMWVrbFoyUFFM
            cTNKSnArdnNmWUVaTkRMbi9qdlBNSDQKciNTRYUTSOaAYy8iElz5bogoN4pBdDpR
            oZ1wLv5AcelEBVWdFdQy1CfHCwY9IiLAnhjft3I5CyiYtDUGCtuRUw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16nln5sa5mc835epftdlg4qr04xacn92fspng2vv9rz3jm995aglqsdjl3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSFl1cC9sQm0xZk5oY3BZ
            V0F6MldSRE9qcDVTUTc1ZlNKbFN4eHhiMW1jCnZhNFN5bmdMaG1qSHdtTDJEMHh5
            SnF4L1oxNlZxSk4wYXlNcGk0b2RQT3MKLS0tIDBSZzdVTWk4TGQvUVBUSjV0dWY1
            TlVuMEViRjJmWjFJK2JMRzdQQVErTkUKUJQX2oiFkv2fhfY8W1R2bcDeoXZeq3T4
            bTfvmaL9Y0zhuqFFxSmOiO51RlNFbBDxiQGvY1s/BbfIbI90MwiTgQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pzsyqcmx4c445pvjyjt0zm84eev3wewwyw6swq44emy8ctn4hfuqhc4dyh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZE9Gc3dpSTRiQys2SVNw
            MU9MRDc1VmxzRVNrbCthQ0gzSzRIWFlqd2hBCnJ3VmI5TGVXNFZmUXoxWVJaRjlz
            RU1sbkZVOStTUGFmWlg5cGRjMDh4WTgKLS0tIFlPVjRlcnRUWWorVWFlT1ovOFZ5
            cG1Pbm1zNzJQSVVoOVFjSEZGY0tXNWMKuGeaP+fBilnjMLhWjECKvh+4XqE3OAG4
            89tGfiRrk2rQweGwlxQp1NulQW1B3Ow8d83E2cAYcrWWKRGzxnC7Jw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1alcamcs84veuatalyac4w9dv33fmsskkcf4vk7x8649we9ew857su566cg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MmYzTVhCZjBIMk0xSDNG
            cEtWWndkQUxNcnRRQmxNUEVmQkI3MEl2K0Y0CmpkVFQybEdRTGF1RjhWeGFKQ3RM
            SGFCaEZIeXN5dm9zc3RoNUJTR3F0T2sKLS0tIElnS0JmRXdXb2xhMitGa2xvNWlJ
            NldHWkJ6MHJYS05Ld2VhTUhadm92QTgKGHe3mZOwLboge3PkXgxEx99X7//UJs4N
            smOH10rjtk0wicpxVpwf/AmlSOpESvr14dGXfpfG7C7rbEfikQ7utA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15sehvxxhnusnhs486we2sznz4736prpf4g5r7ynrycng5xk7f5yss670au
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITlRVUHJBM0FzVks0K0g2
            WGh4YmEvQ3RPT0V5M1RLTVRUNlhwd3dmc0JrCmlhUmw3dFp6MytTckZFMFB6Vy9L
            VGEvbFlzRFZRNmFnY0c1dEhiTEE3aFUKLS0tIE96Ym9nb3MweEp2YnpwNjhZRXlX
            cHdTU3JSSDN1ei9rNmtGQ29QODRCbTgKd50O65/91LJX22pVH+fe+Fsp5q/aODjA
            KzVwdN5yL/nGbYxt2PKEwbZE0rQSzbou5lY5kFLoC0PeJxnXEslsxg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jv72xhzl6scs50q8k689ughewaum7zznk5la5anuxxfxl3cquqasvpdkwd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNDhnU0h3ejk1emV2bjEx
            SzE5QUZrVTNBSVhqNkJ2cjB3WmlhdmM5K3dZCnRUYSticGx0SUxDNjBBWFM5TWhM
            Y2dkSDR1bFBndnFOWlhmaTZJRXVQKzAKLS0tIGpSUXZLMkJoa2ZVczlPSGxXc0cr
            VDI2RS9SWnV6TFZac2xKeDUxZU42VTgK8BrkYXEYBcbnMtZLN49R68Et/s/5tZ+8
            DwA8tQvFPsiTwCN6wUjqe6bC+f+KZ7Ov2jT4OJUinGiQxdjYXe/s2A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wjsewg482wd7dgk04pqspnxyzqjg806zlmmfk8tynar6358yascssl6lg5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WUI5ZG9Vblp6bTByMHBn
            aHZMaXRXU290bXYvamJXalM0aEpxaXdMYVVrCmNlMWxjc3RDamxwUzN3K045TGdk
            ZVBiODRRbGtuc2JVTFVXVk9mQ3lzcW8KLS0tIE9UaUVBVlhqQkpHWUt0MlFWbGZv
            VDJ3WHAvRXdOYjQyK1prREdBTDFBS3MKjM7EgGeQs2ENzwoNW86Ge3xYIDqP/t8M
            EvVTaLYw/16tGncrzhxy06hWJ5+xc/4xFM/eQxezL26FGtgocLaOOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-08T00:06:29Z"
    mac: ENC[AES256_GCM,data:UOoV/Pq4YVPCYj7P/kOL/IXmjLFdTrj5a4WKN0BVa6Pu/dt4JciA41z+/wauywsmItr4n+ymc3sP5UT9uDqA5mXhrXB4O7luKQuO9ycEdMTB5lTiCYQ+FKCXHzFOKMSFOsC1WcKFGXBh3UnrFTOnPWVS8Mi5abRXfasCncVH+vM=,iv:0Qj7q2R8rdo/vL2V62jmLk7UbO2zyPcA/oEDQjeZoxE=,tag:cGZXfk9Fqp2blMlJdHrR4Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
