tailscale: ENC[AES256_GCM,data:UQw5kXkQtGXpJz4LD+RVeaf3AOh+231Tf0lmQXWKVYsHLNeRU7euQqpnWsV3wGk30zSBfgAtNDt0F69vzQ==,iv:MSNIjSX8/yDWSxLYwhxIpFp7BPjmp76+srTvFlTtMGE=,tag:/4IKP+6Kf7ul66+Ef5kRDA==,type:str]
hashed_password: ENC[AES256_GCM,data:R7RdPsOoY+pBWieZ5e5BGWvIfex9ymKKLAtwwc6BN1ltxZdmkEy042XmZExR2Mimvc+EYN0dlo/+eY0XPaO5GuwJ36f9Fw80bWxSc40IcyqGkFYIdMvcKN0y6RE6TfMDsYn0TBd7TZzoDg==,iv:mfBUcyqTXyJEVJgxmxQjbtMKQECNCTXzl1nfFwDsyck=,tag:2zkcy69sNg1LX0v117mf6g==,type:str]
cameron_ssh_key: ENC[AES256_GCM,data:3+ueaPlbS/zNRPEEsLS+txuMN1GCOpzsnZ36dhomlh/emwKAnrN6BZyilpGDWqCYn7Wy5AOHKx9rtBwtL/vaC1X6d/kbwJErLZIEvPY4ElbwMRyPrbKCWCvMviBjRWE79t+hXhbsw8US6YDlqspvrL4x/BvHJg5CHbbYkkjrQxLFUWFzuZeR99Qyo/OP9avGHP3ZO+dONGQuR1TGRG3rSTWboXrNGxehIgHpEZ1UiBjT/CQMH5ycGfxzzVNDRko5++b8o+sqf71ExBNU8lVH8t8LjFklY/zxBPYp3xdWbFMwws8NJT27um6vjRHGE5OG1cy+x4mXLMAWOtSMSSE4ncetB8/uCZEUCaS4JKkXtWf0lb7sMAIIikbtVRf6UBH6G/TLvL4KjvU6dUg3ElXyWKvwRzoFNnCCFrjepdSIe609jjWqu13I6PTYrevmcEyoroMl6D/PMLl7DrnhKC/IXPPn87WUC6neUu4D17bIr7r7yKWQ+7h3MHmC8HJ8yS4UQcRRmxkrRP0tKcq2A/0lckoKoHRdY9FrJzIY,iv:gI1ML9IEbGYaMkbMXvXTANPhu5LfMjRRFSDfGtWPYa8=,tag:4p9oeKMbrExJ+mmLShV/cQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a35mrj6kgp9uvchw8r59q8ma6wdyllmzfyn0ek56ez8jag4gfu4q6rkuuq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSklSN1pnRk9kdW9DY2Ry
            OWhEWm1BNTV6Skxzb3YyNm1IM0E2d2lBa0FFCldRdXNOSkpxV1U4bm8vU1BmVmlk
            V056TjZvaUVFdHo3VFF5aUIyR3JZQ2MKLS0tIEszSHBkaWdRZkp1alUrTmhlRTZF
            MG43RHpXVVo1eWFCL21xSElQMzM1bG8KV94Les31yxK0VzRkJDjprBfsqwsimVcS
            vsK2TqVBY+HkoSJy8hD8lJh0wKqNTHOGps4o+nNeecD29NItx4tbwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vfq6fselrwr9cl3udvx96ldpakzfdhaf8rl5sl9ztg5heq8pjswserwwhe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnS1p1WHFWeGIwZTE0cE9I
            bU5aU0F5RHlIMmZMM3hrdGZuQ0Z2T3VDWXdNCk41ZFFzaWdSdldOUjRFNUQ1Tk9H
            eXFlSjdKd2l1YzA4Z1JhS01sMm84SDQKLS0tIGI1OUNvZ28vNnU0K3k5WWZHNC93
            YVVuS1RteGh5cEhGeEo0N1VZOTNweDQKVIFv7YD8f2igcZUlsHDRXg1ZlY4I0g55
            k6K99fSvxVgKbbtYO4GDdxCpwauZxMLYZexnDTUxkQV4xE61qJi8iA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16nln5sa5mc835epftdlg4qr04xacn92fspng2vv9rz3jm995aglqsdjl3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZXk0QS9YUE9GcERvWW1q
            STVvMTJJaUtqTnNrQlpxRlhyMmk1WHE2QVMwCnQ5d2pZRGY3dkowTFlwWHE5VmQ3
            RHA2ckFtUUdZSmtlSG1YL2JTZWJLbzgKLS0tIEJhZi90TFJseEdDdHFocmdoWDBX
            c05WNVdRa1N6QXJST1NUVUdxOUgxT00KDZRLpOdHdL8M9qbMN3UQPP16/ZMQq1MH
            exUrzE5HnY/51xfmtk9yCWf9hyE+omA+SIVVyw+RZvOM/7c6dh0Bjg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pzsyqcmx4c445pvjyjt0zm84eev3wewwyw6swq44emy8ctn4hfuqhc4dyh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVHE0dE0xR2hTVkdWNnRm
            ZWwzOEFzQlowQzlxQlJXbzZZcGg1REo2ajNZCm45c3NqTlRsQlc3ZGRrK1RyYlJD
            MjBSdUNpQ2p3WlM4T3B4QnJaQkdPcTgKLS0tIGxCTnFwRVl4dkRhdjZZNFhNNGE3
            clFtV0ovZGFPRXpWdm5MRTAwUlVjUFUKx0/pXUug7AA9K0kk0s8BnuJtPySf8Q00
            IJlKhY03tAlnir2yne3K/CvKuVMUB6rck4G3TYtoyJBephVUzsyllQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15sehvxxhnusnhs486we2sznz4736prpf4g5r7ynrycng5xk7f5yss670au
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMnA2Tll3amtuaUlFM3Ev
            M0pjQ0ZBZ0N0K20wWXRockVVZmpOa094KzNnClpkSSsrSnk3Y21YRjVHZHppcUVT
            cWFlODV4a2R4cFQ1MmFTMTVlV0FVbzAKLS0tICt6TG1xdFBpakltQXRUTlpiaVR0
            dzR0Z2t0dU54dno5Q3ZwVkV4NEkySDAKx04YDLb2+aTQBTn0MY+FJaoeSTXqn9Ur
            pglUhqxjkAR3sUliwo22J/7t2AGueCzAns5LKGZtO7vrWnnmEO2zrw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jv72xhzl6scs50q8k689ughewaum7zznk5la5anuxxfxl3cquqasvpdkwd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVUEwRzNlWVhpNWVxdVlC
            SDVTSkU0cjFLUllGdjNVTGlMUXVQMzBrZG1ZCkZ4R25sZndFNDBaQk8wQkduVFlo
            STNoZzVwVkl5NWQ1Ly9nenRiWUwwSjAKLS0tIGphV1ZwNGVzRzg2YVJRV2Rob3Vz
            emo5MFNzMk9YaVY4RmZ4NVBIQTZCVWMKTaiqycQLrT9y4R2xvbCYuGp1uCL/HUp6
            SP8ZqaYtJbCe4+t/11ym0KAqTNNFD+3yXcSdqcNh2kRFjyWWZwxasQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-08T23:09:20Z"
    mac: ENC[AES256_GCM,data:t32CgmpjFZzp/jtSQHR4K//CrLuQ4wgPPMYx4gFUk8LmBUh4SDmDu/qshqg5t7vNeWFXTlHvRuN5d9TKk94FTffPkPXnwj0gD8pWFCE3UFLXd2i/cQVx1bMLVK9mdb7EZ8lhG/s3UtUFC7EsidCeJI4Yh3Bm7d5DmpWOl/ZX3PI=,iv:nZ55H5frwcnETAsZZTUVCc1TflnnR+pD7bZqkBsEfb4=,tag:QOLUw6s10qdoWm3knlPmgw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
