tailscale: ENC[AES256_GCM,data:UQw5kXkQtGXpJz4LD+RVeaf3AOh+231Tf0lmQXWKVYsHLNeRU7euQqpnWsV3wGk30zSBfgAtNDt0F69vzQ==,iv:MSNIjSX8/yDWSxLYwhxIpFp7BPjmp76+srTvFlTtMGE=,tag:/4IKP+6Kf7ul66+Ef5kRDA==,type:str]
hashed_password: ENC[AES256_GCM,data:R7RdPsOoY+pBWieZ5e5BGWvIfex9ymKKLAtwwc6BN1ltxZdmkEy042XmZExR2Mimvc+EYN0dlo/+eY0XPaO5GuwJ36f9Fw80bWxSc40IcyqGkFYIdMvcKN0y6RE6TfMDsYn0TBd7TZzoDg==,iv:mfBUcyqTXyJEVJgxmxQjbtMKQECNCTXzl1nfFwDsyck=,tag:2zkcy69sNg1LX0v117mf6g==,type:str]
cameron_ssh_key: ENC[AES256_GCM,data:3+ueaPlbS/zNRPEEsLS+txuMN1GCOpzsnZ36dhomlh/emwKAnrN6BZyilpGDWqCYn7Wy5AOHKx9rtBwtL/vaC1X6d/kbwJErLZIEvPY4ElbwMRyPrbKCWCvMviBjRWE79t+hXhbsw8US6YDlqspvrL4x/BvHJg5CHbbYkkjrQxLFUWFzuZeR99Qyo/OP9avGHP3ZO+dONGQuR1TGRG3rSTWboXrNGxehIgHpEZ1UiBjT/CQMH5ycGfxzzVNDRko5++b8o+sqf71ExBNU8lVH8t8LjFklY/zxBPYp3xdWbFMwws8NJT27um6vjRHGE5OG1cy+x4mXLMAWOtSMSSE4ncetB8/uCZEUCaS4JKkXtWf0lb7sMAIIikbtVRf6UBH6G/TLvL4KjvU6dUg3ElXyWKvwRzoFNnCCFrjepdSIe609jjWqu13I6PTYrevmcEyoroMl6D/PMLl7DrnhKC/IXPPn87WUC6neUu4D17bIr7r7yKWQ+7h3MHmC8HJ8yS4UQcRRmxkrRP0tKcq2A/0lckoKoHRdY9FrJzIY,iv:gI1ML9IEbGYaMkbMXvXTANPhu5LfMjRRFSDfGtWPYa8=,tag:4p9oeKMbrExJ+mmLShV/cQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a35mrj6kgp9uvchw8r59q8ma6wdyllmzfyn0ek56ez8jag4gfu4q6rkuuq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WnJKclFxTnI2TWdmcFhF
            S1JBWGtvbmlCZUhmVUp5RTFLdEhzdDZkS1djCnFhdXpWUC9WYi84NFVFYmRGSkxn
            ajFkV0xjeDJHMHRKTWorN2NPaVlZTUkKLS0tIHVleDZIUFlSb2hGbVo1WnZ4b1FK
            eXF6T3lneFpJUHI5SUtlUGt2SVlydWcKgW35wK0gBnlPTp9za5vexDx928fq3rxx
            l3k5hiyIvW2OukB0ZRzzt3PBtrZqiXxG8clAIWGt461pCEamKaVh/g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vfq6fselrwr9cl3udvx96ldpakzfdhaf8rl5sl9ztg5heq8pjswserwwhe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMUduaUFFeGU3UHVWRzQv
            bnZVdm1KYkZBTnRoRmxBMi9GdFlqd25DOW1RCmlKSnB6dnR2aDJzeFJRYW1CaEpL
            L1pRTGsrcGMvOHhteHgyV21sTHB2Z1UKLS0tIHNWUGdaakw0aVlsYW13anpyby9u
            RVhzdHBjbG9Bek1pYWNlMWQ5Y0QvOUUK3JRQlHIXw/jodKeOos3DEti0M2iWqKLQ
            UjnYUynIQE54x0EFtlKuE4EeozcTxV8mForUVMUo6Tfk1bAi3aNkUw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16nln5sa5mc835epftdlg4qr04xacn92fspng2vv9rz3jm995aglqsdjl3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdkR5U1dXZDJ0STFYcmNL
            TXdFbUcrV09SVzhibnIvekpaZy9YN3lhSlc0Cjlsdk0ybU5HL0RKaXhpa25XWlk2
            WlFCcWQ2Uk5xUHBicFltU1hlWWFKNE0KLS0tIGpad1Z0T2lEVW5MQWQ2cHFTYy90
            REpJT0hhcTVDdFgrUFVHWCtsMEtweUEKqTQW/w7WP8A3RglIbmRnCHEgpk62/pxj
            KLRVOZ5UkMG23bYuUM4iPXpKqMtd5ouEh/awmB41DttJ4fPOUDRbUQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pzsyqcmx4c445pvjyjt0zm84eev3wewwyw6swq44emy8ctn4hfuqhc4dyh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSzJKeWMwWE9URUdYMjh2
            YmEvM29Pc1Y2Wmtwd0pucHhoNVVIU1ovempFClNUb1pCVW1TeHJtaWtzdFBHZG9C
            ejRIQUN2b0pvK2xaNnFreFN3Y2MybVkKLS0tIGlvYTdoUGhweW9leVUwbkhzRzM0
            RFowTGdJOGs0dmd5VjkzWkRTa0hwWTQKP3ubQ4KQtJimFNyPg0K0om2i7DXKYV7Z
            RnlAbn4+z1LtJ0zvgUJeUtIeZ1rnThCJ+W1fkqbi0x+TJ5Np8p1w1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15sehvxxhnusnhs486we2sznz4736prpf4g5r7ynrycng5xk7f5yss670au
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RDhPRTd6SmZ6U0RZM1V5
            SnhSZmIyenZmSlYzOHMwb1RaWkgycG1OTUVzCk5RenhFZzkweitXRjFZb1BZU2h3
            NWNHSjRreTl6cEJFUmJJcGdpMUNwTDAKLS0tIE5yaXh4a3JEd294c0JubGRUNCt3
            L0ZZc3QyMVJVQ2srdElxZ0R6SHBsWVkKFhLSPpirRchwmqGZIokR35dnD0yeM50D
            4qlyvSdpHSPyWAsrHYEpQ528bViFEe8LZSANq1OPQLCuDEVJ1sCS5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jv72xhzl6scs50q8k689ughewaum7zznk5la5anuxxfxl3cquqasvpdkwd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MHNBWXdHZDcveG1Sa3lM
            am1uNENqd0xnekM4ZnBETE8rajNOSnFtWmpzCmVodnFnRStjRzRUazgwL3FrL0l3
            WFROQjh4TDBUWm5HU3hvT1JKRVFuR3MKLS0tIFlMWG9Gd0JRL01HUDVjZnZJQmdD
            TGJRRXlvaGxpUmVXSVd6b2F1M3E3K1EK4gYnwxV4xfkuitAXwRAOm5ihg40ZQ3I8
            KFyu0LBFUdETV+D4RIlnspZ+i3IfebqdxzG/74zJaAwT9NlogqvGAA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wjsewg482wd7dgk04pqspnxyzqjg806zlmmfk8tynar6358yascssl6lg5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbFMrd2RkaVhwU2Y3L1ZV
            cVptMG9Ddi9Vd3FpWXFneDNQT1pjTkNpQzJNCkFrb2FoanpENUJ2WFU1WWFkT0NX
            LzQ1NEYwcisrQ0RnWG9NNDdsenp3V1EKLS0tIHErRXB5L0d3NEtjZnlqTWVOQ3p5
            dmk4c2N3em11N29ET0ZYNkZXakZxMjQKFJKsRzZyVLEJpbKYb7xwNVsdXMZw44OK
            FyjRQcsxXyc1eMnblLL/YwW83gqFjx6dHVHwp1y8wGjDgbSBjTDO+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-08T23:09:20Z"
    mac: ENC[AES256_GCM,data:t32CgmpjFZzp/jtSQHR4K//CrLuQ4wgPPMYx4gFUk8LmBUh4SDmDu/qshqg5t7vNeWFXTlHvRuN5d9TKk94FTffPkPXnwj0gD8pWFCE3UFLXd2i/cQVx1bMLVK9mdb7EZ8lhG/s3UtUFC7EsidCeJI4Yh3Bm7d5DmpWOl/ZX3PI=,iv:nZ55H5frwcnETAsZZTUVCc1TflnnR+pD7bZqkBsEfb4=,tag:QOLUw6s10qdoWm3knlPmgw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
